baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
# url: "http://squarism.com" # the base hostname & protocol for your site
title: "SQUARISM"

# This is used by feed.xml. Uncomment if you want to use it.
description: "I'm from the valley of the heavy heads."

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Archive
    url: /archive
    external: false
    icon: archive
  - title: About
    url: /about
    external: false
    icon: home
  - title: Talks
    url: /talks
    external: false
    icon: home

projects:
  - title: Dream - A Ruby pixel animation
    url: https://github.com/squarism/dream
  - title: Arduino Cat Faucet
    url: /2011/03/09/arduino-cat-faucet-with-mongodb-and-rails
  - title: Minecraft Metrics with Redis
    url: https://github.com/squarism/minecraft_metrics
  - title: Tatris - A tetris clone
    url: /tatris
  - title: Spikes in the Lab
    url: http://squarism.com/lab

plugins:
  - jemoji
  - jekyll-seo-tag
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: /:year/:month/:day/:title/
excerpt_separator: "<!-- more -->"
future: false
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
