# Site settings
title: [ squarism ]
email: squarism@gmail.com
description: "I'm from the valley of the heavy heads."
baseurl: ""
url: "http://squarism.com/"
twitter_username: squarism
github_username: squarism

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 15
excerpt_separator: "<!-- more -->"